language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "vywei-github"
    token:
      secure: "580ea440dbd893caf84f9bedb4ba171a0168b48b"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
